spring:
  application:
    name: aigateway
  config:
    import: "optional:file:.env[.properties]"
    
  # DATABASE (R2DBC)
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
    
  # Redis Properties
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6380}
      password: ${SPRING_REDIS_PASSWORD:khuong123}
      timeout: 2000ms
      # Redis Connection Optimization
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

  # Config Multi-Provider Routing
  cloud:
    gateway:
      routes:
        # Route dành cho OpenAI
        - id: openai_route
          uri: https://api.openai.com
          predicates:
            - Path=/v1/openai/**
          filters:
            - StripPrefix=2
            
        # Route dành cho Google Gemini
        - id: gemini_route
          uri: https://generativelanguage.googleapis.com
          predicates:
            - Path=/v1/gemini/**
          filters:
            - StripPrefix=2
            
        # Route dành cho Anthropic (Claude)
        - id: anthropic_route
          uri: https://api.anthropic.com
          predicates:
            - Path=/v1/anthropic/**
          filters:
            - StripPrefix=2

# APP
application:
  repository:
    query-limit-warning-ms: ${QUERY_LIMIT_WARNING_MS:1000}

server:
  port: ${SPRING_SERVER_PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Prometheus
management:
  endpoints:
    web:
      exposure:
        include: "gateway" # http://localhost:8080/actuator/gateway/routes
  endpoint:
    gateway:
      enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true